version: '3.9'

services:
  workout-db:
    image: postgres:16.3
    restart: always
    ports:
      - "5000:5432"
    environment:
      POSTGRES_PASSWORD: local_password
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: /home/jose/volumenes/workout-tracker
      o: bind
